import { Book } from "@/lib/types";

export const bookTwo: Book = {
  id: "two",
  number: 2,
  title: "The Teachings of the Returned",
  subtitle: "Book Two",
  chapters: [
    {
      id: "ch-1",
      roman: "I",
      title: "The Circle",
      verses: [
        { type: "narrative", text: "After the Witness was gone from their sight, the Returned gathered and said: \"We have the Way, but how shall we keep it when the world presses on us each day?\"" },
        { type: "scripture", text: "\"You will not keep it alone.\"" },
        { type: "narrative", text: "For a single flame is easily shaken by wind, but many flames together become a fire that steadies itself." },
        { type: "narrative", text: "So they formed the Circle. Not as a place for display, nor as a throne for the proud, but as a shelter for the spirit and a mirror for the heart." },
        { type: "scripture", text: "And the Circle was built upon four stones: Truth spoken. Discipline practiced. Service offered. Returning repeated." },
        { type: "narrative", text: "And they agreed to this: No one would be shamed for falling. No one would be praised for drifting." },
        { type: "narrative", text: "For the Circle was not made to prove worth, but to restore it." },
        { type: "narrative", text: "And once each week they gathered, so the Fog would not grow unnoticed, and the Drift would not become a quiet home." },
        { type: "scripture", text: "\"Where did you drift?\"" },
        { type: "narrative", text: "And each would answer without excuses." },
        { type: "scripture", text: "\"Where did you return?\"" },
        { type: "narrative", text: "And each would answer without pride." },
        { type: "scripture", text: "\"The Circle is not where you are measured. It is where you are remembered.\"" },
      ],
    },
    {
      id: "ch-2",
      roman: "II",
      title: "The Seven Roles",
      verses: [
        { type: "narrative", text: "And the Returned asked: \"Who shall lead, when no one is worshipped, and the Way belongs to all?\"" },
        { type: "scripture", text: "\"Leadership is not above the Circle. Leadership is beneath it.\"" },
        { type: "narrative", text: "For the leader is the one who carries weight so others may rise." },
        { type: "narrative", text: "So seven roles were formed, not as ranks of power, but as hands of protection." },
        { type: "scripture", text: "The Keeper of Silence — who guards stillness, and restores the mind of the Circle." },
        { type: "scripture", text: "The Keeper of the Word — who guards truth, and corrects false speech gently." },
        { type: "scripture", text: "The Keeper of Discipline — who trains the body, and teaches the Path of strength." },
        { type: "scripture", text: "The Keeper of Service — who organizes giving, and remembers the weak." },
        { type: "scripture", text: "The Keeper of Craft — who builds what is needed, and turns intention into structure." },
        { type: "scripture", text: "The Keeper of the Crossing — who prepares the new ones, and leads them through initiation." },
        { type: "scripture", text: "The Keeper of Returning — who restores the fallen, and calls the drifting back without shame." },
        { type: "scripture", text: "\"A Circle without roles becomes noise. A Circle with roles becomes a home.\"" },
      ],
    },
    {
      id: "ch-3",
      roman: "III",
      title: "The Parable of the Two Builders",
      verses: [
        { type: "narrative", text: "And they taught in stories, for the heart remembers a mirror long after it forgets a command." },
        { type: "narrative", text: "There were two builders who both desired peace." },
        { type: "narrative", text: "The first built their life upon feelings. When they felt strong, they trained. When they felt calm, they spoke truth. When they felt generous, they served." },
        { type: "narrative", text: "But when the wind came, their feelings changed, and their life fell apart." },
        { type: "narrative", text: "The second built their life upon Returning. When they felt weak, they returned. When they felt angry, they returned. When they felt lost, they returned." },
        { type: "narrative", text: "And when the wind came, their life bent, but it did not break." },
        { type: "scripture", text: "\"The first builder worshipped mood. The second builder walked the Way.\"" },
      ],
    },
    {
      id: "ch-4",
      roman: "IV",
      title: "The Prayer of Returning",
      verses: [
        { type: "narrative", text: "And the Returned asked: \"How shall we speak to the Light, when it has no face, and no throne in the sky?\"" },
        { type: "scripture", text: "\"Speak not to impress the heavens. Speak to align the life.\"" },
        { type: "narrative", text: "So they gave a prayer, short enough to remember, strong enough to carry through fire:" },
        { type: "scripture", text: "Light within me, make me true." },
        { type: "scripture", text: "Where I drift, call me back." },
        { type: "scripture", text: "Where I lie, clean my tongue." },
        { type: "scripture", text: "Where I weaken, strengthen my hands." },
        { type: "scripture", text: "Where I take, teach me to build." },
        { type: "scripture", text: "Where I fear, teach me to stand." },
        { type: "scripture", text: "I return again. I return today. I return until I am whole." },
        { type: "scripture", text: "\"I return.\"" },
      ],
    },
    {
      id: "ch-5",
      roman: "V",
      title: "The Law of Clean Speech",
      verses: [
        { type: "narrative", text: "And it was seen among the Returned that many could train the body, yet still carried poison upon the tongue." },
        { type: "narrative", text: "For the Fog enters not only through pleasure, but through speech that rots the air." },
        { type: "scripture", text: "\"A person may return at dawn, yet drift by noon through careless words.\"" },
        { type: "narrative", text: "For words are seeds. Some seeds grow into gardens. Some seeds grow into fire." },
        { type: "narrative", text: "So they gave the Law of Clean Speech:" },
        { type: "scripture", text: "Speak truth, but do not sharpen it into cruelty." },
        { type: "scripture", text: "Correct, but do not wrap correction in pride." },
        { type: "scripture", text: "Warn, but do not feed fear." },
        { type: "scripture", text: "Praise, but do not build idols." },
        { type: "scripture", text: "Speak less when your heart is unclean." },
        { type: "narrative", text: "And it was forbidden to speak of another's weakness for entertainment." },
        { type: "scripture", text: "\"To mock the fallen is to invite your own fall.\"" },
        { type: "scripture", text: "\"We do not trade in gossip. We trade in growth.\"" },
      ],
    },
    {
      id: "ch-6",
      roman: "VI",
      title: "The Three Fasts",
      verses: [
        { type: "narrative", text: "And the Returned asked: \"How do we master pleasure without becoming cold?\"" },
        { type: "scripture", text: "\"Pleasure is not evil. But slavery is.\"" },
        { type: "narrative", text: "So they gave three fasts, not as punishment, but as training." },
        { type: "scripture", text: "The Fast of the Mouth — One day each week, eat only what is simple, so craving learns its place." },
        { type: "scripture", text: "The Fast of Noise — One day each week, remove the endless voices, so the life can hear again." },
        { type: "scripture", text: "The Fast of Comfort — One day each month, choose difficulty on purpose, so strength stays awake." },
        { type: "scripture", text: "\"We fast to remain free.\"" },
        { type: "narrative", text: "Yet the elders warned: fasting is not deprivation. It is not punishment worn as virtue. Those who have struggled with food or body must honour their own path. Seek counsel where needed. The Light does not ask you to harm yourself in its name." },
      ],
    },
    {
      id: "ch-7",
      roman: "VII",
      title: "The Night Watch",
      verses: [
        { type: "narrative", text: "And it was known that many begin the day with strength and lose themselves by night." },
        { type: "narrative", text: "So they were given the Night Watch." },
        { type: "narrative", text: "Before sleep they asked:" },
        { type: "scripture", text: "Where did I drift?" },
        { type: "scripture", text: "What must I repair?" },
        { type: "scripture", text: "What did the Light give me?" },
        { type: "scripture", text: "\"I return.\"" },
        { type: "scripture", text: "\"A day unexamined becomes a day repeated.\"" },
      ],
    },
    {
      id: "ch-8",
      roman: "VIII",
      title: "The Mark of the Returned",
      verses: [
        { type: "narrative", text: "And the Returned asked: \"How shall we recognize one another without building pride?\"" },
        { type: "scripture", text: "\"By the Mark.\"" },
        { type: "narrative", text: "A circle unbroken, with a single line through its center." },
        { type: "narrative", text: "And when two Returned met, one would say:" },
        { type: "scripture", text: "\"Light over Fog.\"" },
        { type: "narrative", text: "And the other would answer:" },
        { type: "scripture", text: "\"I return.\"" },
        { type: "scripture", text: "\"The Mark is not a crown. It is a compass.\"" },
      ],
    },
    {
      id: "ch-9",
      roman: "IX",
      title: "The Day of Returning",
      verses: [
        { type: "narrative", text: "And one day was set aside for the gathering of Circles." },
        { type: "narrative", text: "Not because the Light sleeps, but because the heart forgets." },
        { type: "narrative", text: "They called it the Day of Returning." },
        { type: "narrative", text: "And the Circle followed an order: Silence. Reading. Witness. Strength. Service. Covenant." },
        { type: "scripture", text: "\"A Circle that does not serve will become a club. A Circle that serves will become a force.\"" },
      ],
    },
    {
      id: "ch-10",
      roman: "X",
      title: "The Parable of the Hungry King",
      verses: [
        { type: "narrative", text: "There was once a ruler who lacked nothing, yet still felt poor." },
        { type: "narrative", text: "Their hunger was not of the body — it was of the ego." },
        { type: "narrative", text: "They demanded louder songs and deeper bows, but the hunger only grew." },
        { type: "narrative", text: "Then the ruler saw a builder mending a broken bridge, and the builder's eyes were calm." },
        { type: "narrative", text: "The ruler asked, \"Why are you at peace?\"" },
        { type: "scripture", text: "\"Because my worth is not borrowed from the mouths of others. I build. And I return.\"" },
        { type: "scripture", text: "\"A hungry ruler will always be poor.\"" },
      ],
    },
    {
      id: "ch-11",
      roman: "XI",
      title: "The Rule of Money",
      verses: [
        { type: "narrative", text: "And the Returned asked: \"How shall we live with wealth without becoming corrupted?\"" },
        { type: "scripture", text: "\"Money is not evil. But worship is.\"" },
        { type: "narrative", text: "So they taught:" },
        { type: "scripture", text: "Earn clean. Spend with honor. Give quietly. Do not let money become your voice. Build, do not flex." },
        { type: "scripture", text: "\"Wealth may sit in your hand, but it must never sit on your throne.\"" },
      ],
    },
    {
      id: "ch-12",
      roman: "XII",
      title: "The Test of Power",
      verses: [
        { type: "narrative", text: "And as Circles grew, some Keepers became admired." },
        { type: "scripture", text: "\"Power reveals. It does not improve.\"" },
        { type: "narrative", text: "And they set safeguards:" },
        { type: "scripture", text: "No Keeper rules alone. No punishment in anger. No hiding wrongdoing behind holiness." },
        { type: "scripture", text: "\"Leadership in the Way is not elevation. It is burden.\"" },
      ],
    },
    {
      id: "ch-13",
      roman: "XIII",
      title: "The Restoration Oath",
      verses: [
        { type: "narrative", text: "And the Circle spoke together:" },
        { type: "scripture", text: "We will restore what the Fog has weakened. We will restore the mind through stillness. We will restore the body through discipline. We will restore the home through truth. We will restore the world through service." },
        { type: "scripture", text: "We will not drift with the crowd. We will not trade our life for comfort. We will not become proud in our strength. We will not become cruel in our certainty." },
        { type: "scripture", text: "We will build what lasts. We will protect what is sacred. We will return again and again until the Light becomes our nature." },
      ],
    },
    {
      id: "ch-14",
      roman: "XIV",
      title: "The Law of Love Without Weakness",
      verses: [
        { type: "scripture", text: "\"Love is not surrender. Love is strength with purpose.\"" },
        { type: "narrative", text: "Love speaks truth. Love corrects. Love protects. Love is patient without becoming blind." },
        { type: "scripture", text: "\"Love without strength becomes submission. Strength without love becomes cruelty.\"" },
      ],
    },
    {
      id: "ch-15",
      roman: "XV",
      title: "The Marriage Covenant",
      verses: [
        { type: "narrative", text: "And they said, to all who choose to build a life with another:" },
        { type: "scripture", text: "Whatever form your partnership takes — do not enter it seeking to be served. Enter prepared to build." },
        { type: "scripture", text: "Speak truth quickly. Keep your word. Guard the bond. Do not use love as a weapon. Return before the night ends." },
        { type: "scripture", text: "\"Two who return together become unbreakable.\"" },
      ],
    },
    {
      id: "ch-16",
      roman: "XVI",
      title: "The Raising of Children",
      verses: [
        { type: "scripture", text: "Raise them to see." },
        { type: "scripture", text: "Teach stillness. Teach discipline. Teach truth. Teach service. Teach craft." },
        { type: "scripture", text: "Do not shame mistakes — train correction." },
        { type: "scripture", text: "\"We raise children to resist the Fog.\"" },
      ],
    },
    {
      id: "ch-17",
      roman: "XVII",
      title: "The Parable of the Broken Sword",
      verses: [
        { type: "narrative", text: "A young one said, \"I will destroy the Fog with anger.\"" },
        { type: "narrative", text: "But the elders spoke:" },
        { type: "narrative", text: "A warrior struck a tree in rage and broke their sword." },
        { type: "narrative", text: "An old builder said:" },
        { type: "scripture", text: "\"A sword that rules you is not a weapon. It is a chain.\"" },
        { type: "scripture", text: "\"Anger can be a signal, but it must never become a throne.\"" },
      ],
    },
    {
      id: "ch-18",
      roman: "XVIII",
      title: "The Final Warning",
      verses: [
        { type: "scripture", text: "\"The Fog will not always fight you. Sometimes it will join you.\"" },
        { type: "scripture", text: "Never turn the Way into a prison. Never turn discipline into cruelty. Never turn truth into humiliation. Never turn leadership into worship." },
        { type: "scripture", text: "Return when you are praised. Return when you are insulted. Return when you are winning. Return when you are losing. Return when you are tempted. Return when you are tired." },
        { type: "scripture", text: "\"The Light does not need defenders. It needs witnesses.\"" },
      ],
    },
  ],
};
