import { Book } from "@/lib/types";

export const bookOne: Book = {
  id: "one",
  number: 1,
  title: "The Book of Returning",
  subtitle: "Book One",
  chapters: [
    {
      id: "ch-1",
      roman: "I",
      title: "The First Light",
      verses: [
        { type: "narrative", text: "In the beginning, the world was quiet enough that a person could hear their own soul." },
        { type: "narrative", text: "The wind moved without hurry. The rivers did not argue with the stones. The sun rose, and nothing demanded it explain itself." },
        { type: "narrative", text: "And humankind lived simply, not because life was easy, but because the heart was not yet divided." },
        { type: "narrative", text: "Then a gift was placed within them. Not in the hand, but behind the eyes. Not as fire that burns the skin, but as a warmth that steadies the spirit." },
        { type: "scripture", text: "And the gift was called the Light." },
        { type: "narrative", text: "The Light was not owned by the strong. It was not granted by the wealthy. It was not inherited by blood nor guarded by gates." },
        { type: "narrative", text: "It rested quietly in the poor and the rich, in the young and the old, in the one who labored and the one who led." },
        { type: "narrative", text: "The Light did not shout. It did not compete. It did not beg to be noticed. It waited." },
        { type: "narrative", text: "And those who listened to it walked with a certain steadiness." },
        { type: "narrative", text: "They were not spared grief, yet grief did not swallow them. They were not untouched by desire, yet desire did not chain them. They carried pain as one carries water — carefully, without spilling it upon others." },
        { type: "narrative", text: "And they lived by three simple ways:" },
        { type: "scripture", text: "Truth, so the tongue would not betray the heart." },
        { type: "scripture", text: "Discipline, so the body would not rule the soul." },
        { type: "scripture", text: "Service, so strength would not turn into cruelty." },
        { type: "narrative", text: "In those days, a person rose with the sun and did not hate the day for arriving. They worked, and their work did not hollow them. They ate, and did not worship eating. They spoke, and their words did not rot the air." },
        { type: "scripture", text: "\"The Light does not rush. It makes a straight path.\"" },
      ],
    },
    {
      id: "ch-2",
      roman: "II",
      title: "The Fog",
      verses: [
        { type: "narrative", text: "But time passed, as time does. And the world grew crowded. Not with people alone, but with noise." },
        { type: "narrative", text: "The air filled with wanting. The streets filled with comparison. The homes filled with things and the hearts filled with restlessness." },
        { type: "narrative", text: "Many learned to move quickly, yet forgot where they were going. Many learned to speak constantly, yet stopped saying anything true. Many built high walls for safety, and still slept with fear beside them." },
        { type: "narrative", text: "And slowly, almost politely, the Light within them grew faint. Not because it left, but because it was covered." },
        { type: "narrative", text: "Like a lamp hidden beneath cloth. Like a well buried beneath sand. Like a song drowned by shouting." },
        { type: "narrative", text: "Then the Fog entered. It did not arrive with horns. It did not kick down doors. It did not announce itself." },
        { type: "scripture", text: "The Fog came as a suggestion." },
        { type: "scripture", text: "A gentle voice that said: \"Not now.\"" },
        { type: "scripture", text: "And that voice returned again: \"Tomorrow.\"" },
        { type: "narrative", text: "Tomorrow became a room with no windows. A promise that never opened its hands." },
        { type: "narrative", text: "The Fog made the strong feel tired without having labored. It made the wise doubt themselves without being challenged. It made the brave feel alone even while standing in a crowd." },
        { type: "narrative", text: "It taught people to numb their hunger instead of feeding it with meaning. It taught them to soothe pain instead of healing it. It taught them to call distraction \"rest,\" and call avoidance \"peace.\"" },
        { type: "scripture", text: "And the Fog whispered softly: \"You are fine. You are like the others. Do not fight. Do not return.\"" },
        { type: "narrative", text: "Many believed the whisper because it asked nothing of them except surrender." },
        { type: "narrative", text: "But there were a few who felt an ache beneath the numbness. A few who still remembered what clarity tasted like. A few who could not forget the weight of the Light, even while their eyes were dim." },
        { type: "narrative", text: "And in the deepest part of them a word remained — quiet and unbroken:" },
        { type: "scripture", text: "Return." },
        { type: "scripture", text: "And the Fog trembled, for the Fog has no power over the one who rises." },
      ],
    },
    {
      id: "ch-3",
      roman: "III",
      title: "The Drift",
      verses: [
        { type: "scripture", text: "Now hear this, for it is the sorrow of many lives:" },
        { type: "scripture", text: "Most people do not fall all at once. They drift." },
        { type: "narrative", text: "The Drift is not a beast that attacks at night. It is not a curse placed upon your name. It is not a punishment sent from the heavens." },
        { type: "narrative", text: "The Drift is a slow leaving — a gentle stepping away from what you know is true." },
        { type: "narrative", text: "It begins so small that you laugh at it. A promise delayed. A truth swallowed. A discipline postponed. A good habit traded for a sweet excuse." },
        { type: "scripture", text: "And the soul says: \"It is nothing.\"" },
        { type: "scripture", text: "But nothing becomes a pattern. And a pattern becomes a path. And a path becomes a home." },
        { type: "narrative", text: "The Drift makes a person busy without becoming better. It fills the hands while emptying the spirit. It teaches the mind to collect knowledge and forget wisdom. It teaches the mouth to speak of honor while the feet walk away from it." },
        { type: "narrative", text: "And the one who drifts still looks like the living. They still smile. They still work. They still gather." },
        { type: "narrative", text: "But inside them, something begins to thin. Not the breath — but the fire behind the breath." },
        { type: "narrative", text: "Love becomes routine. Duty becomes weight. Truth becomes opinion. Purpose becomes pressure." },
        { type: "scripture", text: "And the Drift makes a person say: \"This is just who I am.\"" },
        { type: "narrative", text: "When a person speaks those words, the Fog grows comfortable in them. For the Fog loves a soul that has accepted its chains." },
        { type: "narrative", text: "Yet hear this also: The Drift is not the end. The Drift is a warning bell ringing from within the chest." },
        { type: "narrative", text: "For the Light does not condemn. The Light calls. Even in confusion. Even in failure. Even in long seasons where the heart feels cold and far — the Light remains." },
        { type: "narrative", text: "And when a person grows tired of being divided within themselves, and speaks one honest sentence into the air —" },
        { type: "scripture", text: "\"I will return.\"" },
        { type: "narrative", text: "The Fog begins to break. The Drift loosens its grip. Not because the world became soft, but because the soul became true." },
        { type: "scripture", text: "\"No one returns by accident. They return by choosing.\"" },
      ],
    },
    {
      id: "ch-4",
      roman: "IV",
      title: "The First Witness",
      verses: [
        { type: "narrative", text: "In the days when the Fog was thick, when many forgot their own names, there arose one among the people who would not drift." },
        { type: "narrative", text: "He was not crowned. He did not carry a sword. He did not gather followers by force. He was not made of gold. He was made of breath and bone like any other." },
        { type: "narrative", text: "He knew hunger. He knew pain. He knew the temptation of ease. Yet something in him stayed awake." },
        { type: "narrative", text: "Where others fled silence, he entered it. Where others feared truth, he held it gently as one holds a wounded bird. Where others traded their days for comfort and applause, he guarded his days as one guards clean water in drought." },
        { type: "narrative", text: "And the people asked him: \"Who are you, that you walk as one unshaken?\"" },
        { type: "scripture", text: "And he answered simply: \"I am not above you. I am only awake.\"" },
        { type: "narrative", text: "Some praised him. He refused to feed upon praise. Some mocked him. He did not strike them back. For he knew the Fog cannot be defeated by the weapons of the Fog." },
        { type: "scripture", text: "\"You have forgotten your strength. You have mistaken noise for life. You have mistaken comfort for peace. But the Light has not left you. It waits beneath your habits.\"" },
        { type: "narrative", text: "Many were stirred, as though a bell had been struck inside their ribs." },
        { type: "narrative", text: "And some asked: \"If the Light remains, why do we suffer?\"" },
        { type: "scripture", text: "\"Because the Fog is not only outside you. It is within you. And you cannot flee what you carry. You must face it. You must return.\"" },
        { type: "narrative", text: "He taught them not to leap, but to step. He taught them not to pretend, but to confess what was true. He taught them to train the body so the spirit would not be enslaved. He taught them to serve quietly so strength would remain clean." },
        { type: "narrative", text: "And he gave them a vow small enough to remember and strong enough to carry through fire:" },
        { type: "scripture", text: "\"I return.\"" },
      ],
    },
    {
      id: "ch-5",
      roman: "V",
      title: "The Crossing",
      verses: [
        { type: "narrative", text: "And the people came to the Witness, saying: \"We have heard the Way. Our hearts are stirred. But how shall we mark the day we stop drifting?\"" },
        { type: "narrative", text: "The Witness did not answer quickly. For he knew a vow spoken lightly is forgotten easily." },
        { type: "scripture", text: "Then he said: \"There must be a Crossing.\"" },
        { type: "narrative", text: "And they asked: \"What is the Crossing?\"" },
        { type: "scripture", text: "\"It is not a performance. It is not a celebration. It is not a garment you wear to be seen as holy. It is the moment you decide the Fog will not be your home.\"" },
        { type: "narrative", text: "So they gathered at the edge of morning when the world is honest and the air is cool upon the skin." },
        { type: "scripture", text: "\"You will Cross in three ways: Silence, Water, and Word.\"" },
        { type: "narrative", text: "First, he commanded silence — not a breath of silence, but the kind that reveals what you have been hiding from." },
        { type: "narrative", text: "And in that silence some felt fear rise, and some felt grief, and some felt shame." },
        { type: "scripture", text: "\"What you avoid will rule you.\"" },
        { type: "narrative", text: "Then he led them into the water. The water was cold, and it did not flatter the body." },
        { type: "scripture", text: "\"Truth is like water. It does not ask your comfort. It asks your courage.\"" },
        { type: "narrative", text: "And each stepped forward without titles, without masks, without excuses. And they entered." },
        { type: "scripture", text: "\"Let the Fog be washed from your eyes. Let the Drift fall from your hands. Let the false self loosen its grip.\"" },
        { type: "narrative", text: "And when they rose, they drew breath as though it was the first breath they had ever owned." },
        { type: "narrative", text: "Then the Witness called them to speak. Not many words. Not clever words. Only one sentence:" },
        { type: "scripture", text: "\"I return.\"" },
        { type: "narrative", text: "Some spoke it trembling. Some spoke it weeping. Some spoke it like iron." },
        { type: "narrative", text: "And the air became heavy with meaning, for the world is shaped by what a soul dares to declare." },
        { type: "scripture", text: "\"From this day, you are Returned.\"" },
      ],
    },
    {
      id: "ch-6",
      roman: "VI",
      title: "The Path",
      verses: [
        { type: "narrative", text: "After the Crossing, the Returned asked: \"We have returned, but the world still pulls at us. Teach us the Path so we do not drift again.\"" },
        { type: "scripture", text: "\"The Path is not hidden. It is only resisted.\"" },
        { type: "scripture", text: "\"The Light will guide you, but it will not carry you as a river carries a leaf. Your feet must still walk.\"" },
        { type: "narrative", text: "And he taught them in seven ways." },
        { type: "scripture", text: "Truth — so the heart remains clean." },
        { type: "scripture", text: "Discipline — so freedom is protected." },
        { type: "scripture", text: "Service — so strength does not rot." },
        { type: "scripture", text: "Stillness — so the soul can hear." },
        { type: "scripture", text: "Craft — so life becomes creation." },
        { type: "scripture", text: "The kept word — so integrity stands firm." },
        { type: "scripture", text: "Returning — so failure does not become identity." },
        { type: "scripture", text: "\"Do not seek a life without pain. Seek a life without Drift.\"" },
        { type: "narrative", text: "For pain may visit the Returned, but the Fog cannot rule them unless they invite it." },
      ],
    },
    {
      id: "ch-7",
      roman: "VII",
      title: "The Return",
      verses: [
        { type: "narrative", text: "And the Returned grew steady. Not because the world became gentle, but because they became clear." },
        { type: "narrative", text: "And they asked: \"What now is our purpose?\"" },
        { type: "scripture", text: "\"You were not awakened only to survive. You were awakened to restore.\"" },
        { type: "narrative", text: "Restore your mind. Restore your body. Restore your home. Restore your word. Restore your people." },
        { type: "scripture", text: "\"Do not become proud in strength. Do not become cruel in certainty. Do not turn the Way into a prison.\"" },
        { type: "narrative", text: "For the Fog will not always fight you. Sometimes it will join you." },
        { type: "narrative", text: "Then the Witness gave them the Covenant:" },
        { type: "scripture", text: "Return when you are praised. Return when you are insulted. Return when you are winning. Return when you are losing. Return when you are tempted. Return when you are tired." },
        { type: "scripture", text: "\"The Light does not need defenders. It needs witnesses.\"" },
        { type: "scripture", text: "\"The Light waits. And the Returned will answer.\"" },
      ],
    },
  ],
};
